apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-oe8e
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mrcc-tenant/rhtap-demo-app/hacbs-test-project-oe8e@sha256:78d8683cabf03c880aa05c49687d1720af822beb32e5b52af3a0f22c1a8bf35e
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
