apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-oe8e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-oe8e
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-oe8e
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-oe8e
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-oe8e
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mrcc-tenant/rhtap-demo-app/hacbs-test-project-oe8e@sha256:c100b62f27dbee7915ea03eebfde94d5ea07ed75d5397859958bc7de7df6ca18
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
